### PR TITLE
Fuzz testing - network layer unit tests with google/gofuzz

### LINKED ISSUE #1596: "keep-core start" terminated with "panic: runtime error: slice bounds out of range"
I started the node with the command `./keep-core start`, and got the error `panic: runtime error: slice bounds out of range` with node termination. Unfortunately, I haven't been able to reproduce this error again. When restarting the node, it started without problems.

The full error log:
```
2020-04-14 02:55:23.603430 DEBUG swarm2 limiter.go:82: [limiter] freeing FD token; waiting: 0; consuming: 6
2020-04-14 02:55:23.603553 DEBUG swarm2 limiter.go:109: [limiter] freeing peer token; peer 16Uiu2HAkxvr9TxpUNSriNWfjX9hfNBzcm1aY4WZJMbFDUtpg4jBa; addr: /ip4/95.165.154.226/tcp/3919; active for peer: 1; waiting on peer limit: 0
panic: runtime error: slice bounds out of range [:32] with capacity 0

goroutine 1447 [running]:
github.com/keep-network/keep-core/pkg/net/security/handshake.(*Act2Message).Unmarshal(0xc000e2c4b0, 0xc000e03ff0, 0xa, 0x10, 0x27, 0xc000e03ff0)
        /home/keep/keep-core/pkg/net/security/handshake/marshaling.go:43 +0xf8
github.com/keep-network/keep-core/pkg/net/libp2p.(*authenticatedConnection).initiatorReceiveAct2(0xc000e303c0, 0x122d4a0, 0xc000d749c0, 0xa, 0x122d4e0, 0xc000d74a00)
        /home/keep/keep-core/pkg/net/libp2p/authenticated_connection.go:243 +0x21c
github.com/keep-network/keep-core/pkg/net/libp2p.(*authenticatedConnection).runHandshakeAsInitiator(0xc000e303c0, 0xc000e303c0, 0x123cb60)
        /home/keep/keep-core/pkg/net/libp2p/authenticated_connection.go:169 +0x24a
github.com/keep-network/keep-core/pkg/net/libp2p.newAuthenticatedOutboundConnection(0x7f8b6c395a68, 0xc0008ccc00, 0xc0000e3050, 0x27, 0x123fd80, 0xc00009a600, 0xc000aaefc0, 0x27, 0x122de60, 0xc00011a5b8, ...)
        /home/keep/keep-core/pkg/net/libp2p/authenticated_connection.go:107 +0x1fd
github.com/keep-network/keep-core/pkg/net/libp2p.(*transport).SecureOutbound(0xc0000c8700, 0x123aae0, 0xc000d6d380, 0x7f8b5e98f1f8, 0xc000e10d80, 0xc000aaefc0, 0x27, 0xc0000c8700, 0x0, 0x0, ...)
        /home/keep/keep-core/pkg/net/libp2p/transport.go:86 +0x14a
github.com/libp2p/go-conn-security-multistream.(*SSMuxer).SecureOutbound(0xc0003ec410, 0x123aae0, 0xc000d6d380, 0x7f8b5e98f1f8, 0xc000e10d80, 0xc000aaefc0, 0x27, 0xe83fa0, 0xf33000, 0xc0000c8800, ...)
        /home/keep/go/pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.1.0/ssms.go:56 +0xf2
github.com/libp2p/go-libp2p-transport-upgrader.(*Upgrader).setupSecurity(0xc0000c8940, 0x123aae0, 0xc000d6d380, 0x7f8b5e98f1f8, 0xc000e10d80, 0xc000aaefc0, 0x27, 0xc00098bc18, 0x8, 0x0, ...)
        /home/keep/go/pkg/mod/github.com/libp2p/go-libp2p-transport-upgrader@v0.1.1/upgrader.go:108 +0x10c
github.com/libp2p/go-libp2p-transport-upgrader.(*Upgrader).upgrade(0xc0000c8940, 0x123aae0, 0xc000d6d380, 0x123cd20, 0xc010a68500, 0x1245a60, 0xc000e10d80, 0xc000aaefc0, 0x27, 0x0, ...)
        /home/keep/go/pkg/mod/github.com/libp2p/go-libp2p-transport-upgrader@v0.1.1/upgrader.go:86 +0x29e
github.com/libp2p/go-libp2p-transport-upgrader.(*Upgrader).UpgradeOutbound(0xc0000c8940, 0x123aae0, 0xc000d6d380, 0x123cd20, 0xc010a68500, 0x1245a60, 0xc000e10d80, 0xc000aaefc0, 0x27, 0x10, ...)
        /home/keep/go/pkg/mod/github.com/libp2p/go-libp2p-transport-upgrader@v0.1.1/upgrader.go:57 +0xcf
github.com/libp2p/go-tcp-transport.(*TcpTransport).Dial(0xc010a68500, 0x123aae0, 0xc000d6d380, 0x1248160, 0xc0000d1760, 0xc000aaefc0, 0x27, 0xc000e14020, 0xc000910e38, 0x4fde52, ...)
        /home/keep/go/pkg/mod/github.com/libp2p/go-tcp-transport@v0.1.1/tcp.go:107 +0x156
github.com/libp2p/go-libp2p-swarm.(*Swarm).dialAddr(0xc000083980, 0x123aae0, 0xc000d6d380, 0xc000aaefc0, 0x27, 0x1248160, 0xc0000d1760, 0x1c1e140, 0x123aae0, 0xc000d6d380, ...)
        /home/keep/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_dial.go:462 +0x219
github.com/libp2p/go-libp2p-swarm.(*dialLimiter).executeDial(0xc0003ec230, 0xc000d746c0)
        /home/keep/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/limiter.go:218 +0x16a
created by github.com/libp2p/go-libp2p-swarm.(*dialLimiter).addCheckFdLimit
        /home/keep/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/limiter.go:168 +0x5ff
```

### PR DESCRIPTION
**Pull request by lukasz-zimnoch**
Refs https://github.com/keep-network/keep-ecdsa/issues/389
Closes #1596

Here we add some fuzz unit tests scenarios to make sure network layer types are marshaled and unmarshaled correctly under various conditions and cause no unexpected panics. Specifically added fuzzing tests for:
- DKG protocol messages unmarshalers
- Relay entry signing messages unmarshalers
- Handshake messages unmarshalers. Detected and repaired some failing cases here.
- Broadcast and unicast channels with randomly generated messages.

### CODE REVIEW

File: pkg/internal/pbutils/pbutils.go [hunk 1]
```diff
@@ -27,3 +30,15 @@ func RoundTrip(
...
+func FuzzUnmarshaler(unmarshaler proto.Unmarshaler) {
+	for i := 0; i < 100000; i++ {
+		var messageBytes []byte
+
+		f := fuzz.New().NilChance(0.1).NumElements(0, 512)
+		f.Fuzz(&messageBytes)
+
+		_ = unmarshaler.Unmarshal(messageBytes)
+	}
+}
```
[the remark this answers is not in the document]
Comment (lukasz-zimnoch) [reply pkg/internal/pbutils/pbutils.go:44]: Yeah, I thought about this initially but encountered a big problem: this fuzzer can't fill private fields in our messages. Do you think we can make them all public?

[the remark this answers is not in the document]
Comment (lukasz-zimnoch) [reply pkg/internal/pbutils/pbutils.go:44]: Anyway, I found out I can fuzz individual fields separately and use them to create specific messages. This seems inconvenient but it's the only possibility here.

File: pkg/net/libp2p/channels_fuzzing_test.go [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+		provider2 net.Provider,
+	) {
+		channel, err := provider1.UnicastChannelWith(identity2.id)
+		if err != nil {
+			t.Fatal(err)
+		}
+
+		provider2.OnUnicastChannelOpened(func(channel net.UnicastChannel) {
+			channel.SetUnmarshaler(func() net.TaggedUnmarshaler {
+				return &fuzzingMessage{}
```
Comment (pdyraga) [inline pkg/net/libp2p/channels_fuzzing_test.go:27]: Per our [previous discussion](https://github.com/keep-network/keep-core/pull/1599/files#r408862061), I think we should rather fuzz on `*pb.UnicastNetworkMessage` as this type is what we are processing in `processMessage` of `unicastChannel`. Random bytes are fine but I don't think it give us any advantage to generate more than 10 random cases. 

I think we should also call `processMessage` directly. We are probably more interested in fuzz-testing receive part than the send part. All marshallers will have a roundtrip fuzz tests and send is covered with unit tests for a happy path, I think it's enough.

Comment (pdyraga) [reply pkg/net/libp2p/channels_fuzzing_test.go:27]: Same for the broadcast channel part below.

Comment (lukasz-zimnoch) [reply pkg/net/libp2p/channels_fuzzing_test.go:27]: We are not only testing the send part here but the receive part as well because each generated byte slice pass through the whole channel. Though, I think we can direct `processMessage` fuzzing for better coverage.

Comment (pdyraga) [reply pkg/net/libp2p/channels_fuzzing_test.go:27]: OK, let's leave it as-is, this is covering `handleStream` function in the unicast channel and `processPubsubMessage` in the broadcast channel. Though I think we should reduce it to the minimum, e.g. `10` fuzzing iterations with `0.1` nil chance and add separate fuzzing for `processMessage` as you suggested.

**Comment by lukasz-zimnoch** [comment]
@pdyraga I'm ready for another round!
